//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorporacionInforme
    {
        public long IdInformeCorporacion { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> IdGroupInforme { get; set; }
        public string ObjetivoDelAporte { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public Nullable<long> MontoAportado { get; set; }
    }
}
