//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastoInformev2
    {
        public long IdGastoInforme { get; set; }
        public string Codigo { get; set; }
        public string Cuenta { get; set; }
        public Nullable<double> MontoPresupuestado { get; set; }
        public Nullable<double> MontoGastado { get; set; }
        public Nullable<System.DateTime> UpdatedOnUTC { get; set; }
        public Nullable<System.Guid> IdGroupInformeGasto { get; set; }
        public Nullable<int> TipoCodigo { get; set; }
        public string TipoNombre { get; set; }
    }
}
