//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingreso_Glosa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingreso_Glosa()
        {
            this.Ingreso_GlosaCodigo = new HashSet<Ingreso_GlosaCodigo>();
        }
    
        public long GlosaId { get; set; }
        public string NombreAreaNivel2 { get; set; }
        public string NombreCuentaNivel1 { get; set; }
        public string NombreCuentaNivel2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingreso_GlosaCodigo> Ingreso_GlosaCodigo { get; set; }
    }
}
