//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal_SaludInforme
    {
        public long IdInformePersonal { get; set; }
        public Nullable<System.Guid> IdGroupInformePersonal { get; set; }
        public string Genero { get; set; }
        public Nullable<int> Edad { get; set; }
        public string CalidadJuridica { get; set; }
        public string Profesion { get; set; }
        public string NivelAcademico { get; set; }
        public string Estamento { get; set; }
        public Nullable<int> Grado { get; set; }
        public string Antiguedad { get; set; }
        public string Area { get; set; }
        public Nullable<long> SueldoHaberes { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
