//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor_Cementerio_Nivel2
    {
        public long IdNivel2 { get; set; }
        public Nullable<long> IdNIvel1 { get; set; }
        public string Nombre { get; set; }
        public Nullable<long> Monto { get; set; }
        public string Area { get; set; }
        public string Glosa { get; set; }
    
        public virtual Proveedor_Cementerio_Nivel1 Proveedor_Cementerio_Nivel1 { get; set; }
    }
}
