//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor_SaludInforme
    {
        public long IdInformeProveedores { get; set; }
        public Nullable<System.Guid> IdGroupInformeProveedores { get; set; }
        public Nullable<long> NumeroOrdenCompra { get; set; }
        public string Glosa { get; set; }
        public string Proveedor { get; set; }
        public string Rut { get; set; }
        public Nullable<long> Monto { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
